[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize --fpm-config /usr/local/etc/php-fpm.conf
numprocs=1
autostart=true
autorestart=true
autorestart=unexpected
exitcodes=0
stderr_logfile=/var/log/php-fpm_supervisor.err.log
stdout_logfile=/var/log/php-fpm_supervisor.out.log
priority=100
